server:
  port: 8082


spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/productcatalogue?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true