server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared   #tells spring where to locate the config files
  profiles:
    active: native    #using native because the config server uses a git repo by default
  security:
    user:
      password: 1234   #the password which apps will use to access its configurations
